import './globals.css'
import Navbar from './Navbar';

export const metadata = {
  title: 'Tarea 4.1. Uso de App Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
